<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OptcgExplorer.Infrastructure\OptcgExplorer.Infrastructure.csproj" />
    <ProjectReference Include="..\OptcgExplorer.UseCases\OptcgExplorer.UseCases.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Components\Features\DonCards\" />
  </ItemGroup>

</Project>
